version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: test
    ports:
      - "5432:5432"

  test:
    image: testgraal:0.0.1-SNAPSHOT
    platform: linux/arm64
    ports:
      - "8080:8080"
