name: Deploy TestGraal

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan -input=false \
          -var "resource_group_name=testgraal-rg" \
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -input=false tfplan
        working-directory: terraform

  container:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v3
        with:
          name: latest-tag

      - name: Load Latest Tag
        run: |
          export LATEST_TAG=$(cat latest-tag.txt)
          echo "Latest tag is $LATEST_TAG"     

      - name: Pull Docker Image to GitHub Container Registry
        run: |
          docker pull ghcr.io/markducommun/testgraal-image:$LATEST_TAG
          az acr login --name ${{ secrets.AZURE_ACR_NAME }}
          docker tag ghcr.io/markducommun/testgraal-image:$LATEST_TAG ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/testgraal-image:$LATEST_TAG

