name: Deploy TestGraal Azure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  provision-infrastructure:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan -input=false \
          -var "resource_group_name=testgraal-rg" \
        working-directory: terraform

      - name: Terraform Apply
        id: registry-terraform
        run: terraform apply -input=false tfplan
        working-directory: terraform

      - name: Capture Terraform Output
        id: get_output
        run: terraform output -json > terraform_output.json
        working-directory: terraform

      - name: Set Terraform Output as Environment Variable
        run: |
          export REGISTRY_NAME=$(cat terraform_output.json | jq -r '.registry_name.value')
          echo "REGISTRY_NAME=$REGISTRY_NAME" >> $GITHUB_ENV
          echo "REGISTRY_NAME=$REGISTRY_NAME"  
          export REGISTRY_LOGIN_SERVER=$(cat terraform_output.json | jq -r '.registry_login_server.value')
          echo "REGISTRY_LOGIN_SERVER=$REGISTRY_LOGIN_SERVER" >> $GITHUB_ENV
          echo "REGISTRY_LOGIN_SERVER=$REGISTRY_LOGIN_SERVER"  

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v3
        with:
          name: latest-tag

      - name: Load Latest Tag
        run: |
          export LATEST_TAG=$(cat latest-tag.txt)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest tag is $LATEST_TAG"   

      - name: Azure Registry Login
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: az acr login --name $REGISTRY_NAME

      - name: Pull Docker Image to GitHub Container Registry
        run: |
          docker pull ghcr.io/markducommun/testgraal-image:$LATEST_TAG

      - name: Tag Docker Image
        run: |  
          docker tag ghcr.io/markducommun/testgraal-image:$LATEST_TAG $REGISTRY_LOGIN_SERVER/testgraal-image:$LATEST_TAG


      - name: Create folder structure
        run: |
          mkdir -p TestgraalApp/handler

      - name: Move executable and configuration files
        run: |
          mv build/native/nativeCompile/testgraal TestgraalApp/handler/
          mv azure-executable/function.json TestgraalApp/handler/
          mv azure-executable/host.json TestgraalApp/handler/

      - name: Zip the TestgraalApp directory
        run: |
          zip -r TestgraalApp.zip TestgraalApp
