name: Deploy Testgraal Azure Function Executable

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  provision-infrastructure:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan -input=false \
          -var "resource_group_name=testgraal-executable-rg" \
          -var "function_app_name=testgraal-executable-functionapp" \
        working-directory: terraform

      - name: Terraform Apply
        id: registry-terraform
        run: terraform apply -input=false tfplan
        working-directory: terraform

      - uses: actions/download-artifact@v3
        with:
          name: testgraal-executable

      - name: Create folder structure
        run: |
          mkdir -p TestgraalApp/handler

      - name: Move executable and configuration files
        run: |
          mv testgraal-executable TestgraalApp/handler/
          mv azure-executable/function.json TestgraalApp/handler/
          mv azure-executable/host.json TestgraalApp/handler/

      - name: Zip the TestgraalApp directory
        run: |
          zip -r TestgraalApp.zip TestgraalApp

      - name: Upload TestgraalApp.zip as Artifact
        run: |
          az functionapp deployment source config-zip \
            --resource-group testgraal-executable-rg \
            --name testgraal-executable-functionapp \
            --src functionapp-testgraal.zip
