name: Deploy Testgraal Azure Function Executable

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  provision-infrastructure:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform-azure-executable

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan -input=false \
          -var "resource_group_name=testgraal-executable-rg" \
          -var "function_app_name=testgraal-executable-functionapp" \
        working-directory: terraform-azure-executable

      - name: Terraform Apply
        id: registry-terraform
        run: terraform apply -input=false tfplan
        working-directory: terraform-azure-executable

  deploy-executable:
    runs-on: ubuntu-latest
    needs: provision-infrastructure
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find the Last Workflow Run ID with Desired Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: find-run-id
        run: |
          # Get the latest workflow runs
          WORKFLOW_RUNS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs")

          # Iterate through workflow runs to find the artifact
          for RUN_ID in $(echo "$WORKFLOW_RUNS" | jq -r '.workflow_runs[] |select(.name=="Build GraalVM Executable") |  select(.status=="completed") | .id'); do

          echo "Checking run ID: $RUN_ID"
          ARTIFACTS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/artifacts")

          # Check if the desired artifact exists
          ARTIFACT_URL=$(echo "$ARTIFACTS" | jq -r '.artifacts[] | select(.name=="testgraal-executable") | .archive_download_url')

          if [[ -n "$ARTIFACT_URL" ]]; then
          curl -L -H "Authorization: Bearer $GITHUB_TOKEN" -o testgraal-executable.zip $ARTIFACT_URL
          break
          fi
          done

          if [[ -z "$$ARCHIVE_DOWNLOAD_URL" ]]; then
          echo "Error: Artifact 'testgraal-executable' not found in recent workflow runs." >&2
          exit 1
          fi

      - name: Extract Artifact
        run: unzip testgraal-executable.zip

      - name: Create folder structure
        run: |
          mkdir -p TestgraalApp/root

      - name: Move executable and configuration files
        run: |
          mv testgraal TestgraalApp/
          mv azure-executable/root/function.json TestgraalApp/root/function.json
          mv azure-executable/host.json TestgraalApp/host.json

      - name: Zip the TestgraalApp directory
        run: |
          zip -r TestgraalApp.zip TestgraalApp

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Function'
        uses: Azure/functions-action@v1
        with:
          app-name: testgraal-executable-functionapp
          package: TestgraalApp.zip

#      - name: Upload TestgraalApp.zip as Artifact
#        run: |
#          az functionapp deployment source config-zip \
#            --resource-group testgraal-executable-rg \
#            --name testgraal-executable-functionapp \
#            --src TestgraalApp.zip

